// src/config.js

export const DEFAULT_PARAMS = {
  putTickers: 'AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,ANSS,ASML,AVGO,AZN,BIIB,BKNG,BKR,CDNS,CDW,CEG,CHTR,CMCSA,COST,CPRT,CRWD,CSCO,CSGP,CSX,CTAS,CTSH,DASH,DDOG,DLTR,DXCM,EA,EXC,FANG,FAST,FTNT,GEHC,GILD,GOOG,GOOGL,HON,IDXX,ILMN,INTC,INTU,ISRG,KDP,KHC,KLAC,LRCX,LULU,MAR,MCHP,MDLZ,MELI,META,MNST,MRNA,MRVL,MSFT,MU,NFLX,NVDA,NXPI,ODFL,ON,ORLY,PANW,PAYX,PCAR,PDD,PEP,PLTR,PYPL,QCOM,REGN,ROP,ROST,SBUX,SIRI,SNPS,SPLK,TTD,TTWO,TXN,VRSK,VRTX,WBA,WBD,WDAY,XEL,ZM',
  callTickers: 'QQQ',
  filters: {
    DTE_MIN: 25,
    DTE_MAX: 50,
    MIN_VOLUME: 100,
    MIN_OPEN_INTEREST: 500,
    PUT_DELTA_MIN: 0.12,
    PUT_DELTA_MAX: 0.30,
    CALL_DELTA_MIN: 0.12,
    CALL_DELTA_MAX: 0.30,
    PUT_OTM_PERCENT_MIN: 5.0,
    PUT_OTM_PERCENT_MAX: 15.0,
    CALL_OTM_PERCENT_MIN: 5.0,
    CALL_OTM_PERCENT_MAX: 15.0,
  }
};
